#!/bin/bash
set -x

if [ ! -d $OPENSHIFT_DATA_DIR/m2/repository ]
        then
                cd $OPENSHIFT_DATA_DIR
				mkdir m2/repository                
fi

if [ ! -d $OPENSHIFT_DATA_DIR/logs ]
        then
                cd $OPENSHIFT_DATA_DIR
				mkdir logs
fi

if [ ! -d $OPENSHIFT_DATA_DIR/jdk1.8.0_71 ]
        then
                cd $OPENSHIFT_DATA_DIR
                #wget http://download.oracle.com/otn-pub/java/jdk/8u71-b15/jdk-8u71-linux-x64.tar.gz
                tar xvf *.tar.gz
                rm -f *.tar.gz
fi

if [ ! -d $OPENSHIFT_DATA_DIR/apache-maven-3.3.9 ]
        then
                cd $OPENSHIFT_DATA_DIR
                wget http://ftp.unicamp.br/pub/apache/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz
                tar xvf *.tar.gz
                rm -f *.tar.gz
fi


cd $OPENSHIFT_REPO_DIR
export M2=$OPENSHIFT_DATA_DIR/apache-maven-3.3.9/bin
export MAVEN_OPTS="-Xms384m -Xmx412m"
export JAVA_HOME=$OPENSHIFT_DATA_DIR/jdk1.8.0_71
export PATH=$JAVA_HOME/bin:$M2:$PATH

mvn -s settings.xml clean install